AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Multi-Function Lambda API

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Architectures:
      - arm64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Stage
  Api:
    Auth:
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt CognitoUserPool.Arn

Parameters:
  Stage:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    Description: API Gateway Stage Name

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "${AWS::StackName}-client"
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-layer
      Description: Common utilities and dependencies
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-items"
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.hello.app.lambda_handler
      Tags:
        Environment: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  GoodbyeWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.goodbye.app.lambda_handler
      Tags:
        Environment: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Events:
        GoodbyeWorld:
          Type: Api
          Properties:
            Path: /goodbye
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

  HelloItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.hello_item.app.lambda_handler
      Tags:
        Environment: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          ITEMS_TABLE: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        HelloItem:
          Type: Api
          Properties:
            Path: /hello/{itemId}
            Method: get

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  GoodbyeWorldFunction:
    Description: "Goodbye World Lambda Function ARN"
    Value: !GetAtt GoodbyeWorldFunction.Arn
  CommonLayer:
    Description: "Common Layer ARN"
    Value: !Ref CommonLayer
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
  ItemsTable:
    Description: "Items DynamoDB Table Name"
    Value: !Ref ItemsTable
