AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Multi-Function Lambda API

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Architectures:
      - arm64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Stage

Parameters:
  Stage:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    Description: API Gateway Stage Name

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.hello.app.lambda_handler
      Tags:
        Environment: !Ref Stage
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  GoodbyeWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: functions.goodbye.app.lambda_handler
      Tags:
        Environment: !Ref Stage
      Events:
        GoodbyeWorld:
          Type: Api
          Properties:
            Path: /goodbye
            Method: get

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  GoodbyeWorldFunction:
    Description: "Goodbye World Lambda Function ARN"
    Value: !GetAtt GoodbyeWorldFunction.Arn
